### ISSUE TITLE
'TypeError: Can not read property' files 'of undefined' error when exist a hidden folder.

### ISSUE THREAD

**Issue by hmu332233** [AckerApple/path-reader#4]
I executed 'git clone'

Next, I ran 'dir.files ()' as the path to this folder
An error such as 'TypeError: Can not read property' files 'of undefined' has occurred.

(I thinked it happens when there is a hidden folder like '.git')

So I removed '.git' and ran it again
it work fine.

needs fix

**Comment by AckerApple** [comment]
An option exists of "excludeHidden", maybe that will help?

I don't seem to have a unit test for reading hidden folders so can't argue with you.

Feel free to fix and make a pull request. I'll leave this issue open until one of us get to it.

**Comment by AckerApple** [comment]
Also, far more details like a stack trace would really help. The lack of details gives me no drive to up and magically fix.

**Comment by hmu332233** [comment]
Sorry..
Hidden folders did not cause an error.

'dir.files()' displays an error if there is a folder that does not have any files in the path
```
dir.files('/test_dir', {sync:true});

test_dir
|-- test.js
|-- aaa
|-- bbb
|   |-- test.js
```

error message
```
/workspace/markdown_navigator/node_modules/path-reader/lib/paths.js:114
  results.files = results.files.concat(res.files);  
                                          ^

TypeError: Cannot read property 'files' of undefined
  at subloop (/workspace/test/node_modules/path-reader/lib/paths.js:114:57)
  at /workspace/test/node_modules/path-reader/lib/paths.js:130:13
  at onDirRead (/workspace/test/node_modules/path-reader/lib/paths.js:188:54)
  at onStat (/workspace/test/node_modules/path-reader/lib/paths.js:203:14)
  at Object.files (/workspace/test/node_modules/path-reader/lib/paths.js:211:12)
  at Object.create_index (/workspace/test/lib/markdown_navigator.js:12:32)
  at Object.<anonymous> (/workspace/test/lib/app.js:25:22)at apply (/workspace/markdown_navigator/node_modules/director/lib/director/router.js:448:19)
  at _every (/workspace/test/node_modules/director/lib/director/router.js:30:9)
  at Router.invoke (/workspace/test/node_modules/director/lib/director/router.js:454:5)
```

**Comment by AckerApple** [comment]
With these details I think I could fix and provide a unit test by or on Monday. No promises

**Comment by AckerApple** [comment]
Get latest version. Try again. Report and/or close issue.

A unit test for this has been created

**Comment by hmu332233** [comment]
Thanks!

No more errors occur.

But is 'undefined' intentional?

---
```
test_dir
|-- test.js
|-- aaa
|-- .test
|   |-- test.js
```
```
var files = dir.files('/test_dir', {sync:true});
console.log(files);

[ 'test_dir/.test/test.js', undefined, 'test_dir/test.js' ]
```

**Comment by AckerApple** [comment]
Alrighty, leave this issue open. It seems we need another unit test for folders inside folders that have no items. My test was only for immediate folders with no items.

Will work it out in a few days. Please feel free to message again if I take too long.

**Comment by AckerApple** [comment]
Fixed and tests created. Only place I see possible undefined to occur is if `type=combine` which combines results of directors and files into one metadata object.

Please check for yourself and close.

Side note, I'm so work for salesmen that don't know tech. Keep an ear out for me for anyone looking for an Angular/NodeJs talent.

**Comment by hmu332233** [comment]
Everything works fine.
Thank you!

**Comment by aravindhan32** [comment]
hi All,
I am getting this error and i am new to angular. i can't able to figure it out what is the error. And i have done search in google. Still i can't able to find out the solution

Error: (./node_modules/path-reader/lib/paths.js
Module not found: Error: Can't resolve 'fs' )

**Comment by AckerApple** [comment]
This is not an Angular package.

I do maintain an Angular file package you might be interested in: 
https://www.npmjs.com/package/angular-file
