### ISSUE TITLE
Cannot use the module two times in a row

### ISSUE THREAD

**Issue by jontxo** [AckerApple/path-reader#6]
Hello

I am using your module in the following node js code (first version) and it works correctly in the first call, but the second one fails without any error. If I change the name of the variable that has the module path-reader (second version) then the module works correctly. I thing that there is something that has to be deleted in order to be able to use the module a second time but I don't know exactly what it is.

-- first version
`    var pathReader = require('path-reader');
    var result = await pathReader.promiseFiles(config.report.parameters.featuresFolder)
    .catch(e=>console.error(e));

    var pathReader = require('path-reader');
    var result1  = await pathReader.promiseFiles(config.report.parameters.featuresFolder)
    .catch(e=>console.error(e));`

-- second version
`
    var pathReader = require('path-reader');
    var result = await pathReader.promiseFiles(config.report.parameters.featuresFolder)
    .catch(e=>console.error(e));

    var pathReader = require('path-reader');
    var result1  = await pathReader.promiseFiles(config.report.parameters.featuresFolder)
    .catch(e=>console.error(e));
`

with visual studio code 1.28.2 and node 8.9.3

and the following launch configuration
`
 {
            "type": "node",
            "request": "launch",
            "name": "Generate Report",
            "cwd": "${workspaceRoot}",
            "protocol": "inspector",
            "runtimeArgs": [
                "inspect"
            ],
            "program": "${workspaceFolder}/test/test.js"
        }
`
and the following package.json
`
{
  "name": "multiple-cucumber-html-reporter",
  "version": "1.3.0",
  "description": "Generate beautifull cucumberjs reports for multiple instances (browsers / devices)",
  "keywords": [
    "cucumber",
    "html",
    "test report",
    "multiple-cucumber-html-reporter",
    "html report",
    "json to html"
  ],
  "main": "lib/generate-report.js",
  "scripts": {
    "test": "jasmine",
    "unit.test.coverage": "JASMINE_CONFIG_PATH=test/unit/jasmine.json istanbul cover jasmine",
    "coveralls": "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage",
    "dev": "nodemon server.js",
    "test-cover": "NODE_ENV=test nyc --clean --reporter=lcov --reporter=json --reporter=text npm test "
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/wswebcreation/multiple-cucumber-html-reporter.git"
  },
  "author": "wswebcreation",
  "bugs": {
    "url": "https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues"
  },
  "homepage": "https://github.com/wswebcreation/multiple-cucumber-html-reporter#readme",
  "dependencies": {
    "adm-zip": "^0.4.7",
    "async": "^2.6.1",
    "bluebird": "^3.5.2",
    "body-parser": "^1.18.2",
    "bson": "^3.0.2",
    "c21e": "^1.1.5",
    "chalk": "2.4.1",
    "clear-require": "^2.0.0",
    "cucumber-messages": "^2.0.0",
    "date-and-time": "^0.6.3",
    "ejs": "^2.5.8",
    "express": "^4.16.3",
    "find": "^0.2.9",
    "fs-extra": "^7.0.0",
    "fs-promise": "^2.0.3",
    "gherkin": "^5.1.0",
    "helmet-csp": "^2.7.0",
    "js-base64": "^2.4.9",
    "json-future": "^2.1.3",
    "jsonfile": "5.0.0",
    "jszip": "^3.1.5",
    "klaw": "^3.0.0",
    "lodash": "^4.17.11",
    "minimist": "^1.2.0",
    "minipass": "^2.3.5",
    "mkdir": "0.0.2",
    "mkdirp": "^0.5.1",
    "mongodb": "^3.0.5",
    "opn": "^5.4.0",
    "path-reader": "^1.1.0",
    "proxyquire": "^2.1.0",
    "recursive-readdir": "^2.2.2",
    "require-and-forget": "^1.0.0",
    "safe-buffer": "^5.1.2",
    "tar": "^4.4.1",
    "util": "^0.11.0",
    "uuid": "^3.3.2",
    "winston": "^3.1.0",
    "yallist": "^3.0.2"
  },
  "devDependencies": {
    "coveralls": "^3.0.2",
    "istanbul": "0.4.5",
    "jasmine": "^3.3.0",
    "jasmine-console-reporter": "^3.1.0",
    "jasmine-expect": "^3.8.4",
    "nodemon": "^1.18.5",
    "nyc": "^13.1.0",
    "supertest": "^3.3.0"
  },
  "directories": {
    "doc": "docs",
    "lib": "lib",
    "test": "test"
  },
  "license": "ISC"
}

`

**Comment by AckerApple** [comment]
SOOOOOOOOooooooooo, I wish I had a softer way to say this but please understand I am a very direct person who wants to get to the point of things very fast ... My point is: I don't trust that you know what you are doing.

My opinion is made up by the provided code sample, lack of legit github icon, young age low activity of github account, and a few other judgements that I could be wrong about. I do apologize where I am wrong but I ran tests and I have unit tests and this code is proving stable even against your reported "issue".

Your code has the keyword `await` before promises that are firing and when I copy/paste your code I directly get errors of `await is only valid in async function`. When I remove the awaits and run normal Promise based `then()` functionality, everything checks out. Maybe instead of `promiseFiles` you might be interested in the callback version of `readFiles` maybe but I doubt that's what you need in the end.

Either way, I will require you to work harder to prove your case. This code is used in production and has settled for sometime with no changes needed.

My next comment will be the end code I used to test your claim

**Comment by AckerApple** [comment]
The code I used to test this reported issue:


```
var dir = __dirname

//-- first version
var pathReader = require('path-reader');
var result = pathReader.promiseFiles(dir)
.then(function(x){
  console.log('x0',x)
})
.catch(e=>console.error(e));

var pathReader = require('path-reader');
var result1  = pathReader.promiseFiles(dir)
.then(function(x){
  console.log('x1',x)
})
.catch(e=>console.error(e));

//-- second version
var pathReader = require('path-reader');
var result = pathReader.promiseFiles(dir)
.then(function(x){
  console.log('x2',x)
})
.catch(e=>console.error(e));

var pathReader = require('path-reader');
var result1 = pathReader.promiseFiles(dir)
.then(function(x){
  console.log('x3 Mayp',x)
})
.catch(e=>console.error(e));
```

**Comment by jontxo** [comment]
Hello

The problem was solved after removing some node modules from my project.

Regards

**Comment by AckerApple** [comment]
Great to hear. Before you report your next issue, may I recommend you update to a legit icon of yourself. When I couldn't replicate your issue, I severally leaned on judging you and forming opinions just to discredit the realness of your issue... I am glad I did, I know this package to be well tested.

Farewell new friend
